### ISSUE TITLE
Browsermob issue 

### ISSUE THREAD

**Issue by rosie78** [rosie78/selenium-framework#1]
Hi all,
When I use HtmlUnitDriver, i got this error 

java.lang.NoSuchMethodError: org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)V   

The root cause is because **UrlEncoded.deCodeTo** method from **BrowserMobHttpClient** is referred , but Maven compiler called to **deCodeTo** method from **org.eclipse.jetty**,

 I tried to exclude the org.eclipse.jetty.jetty-util in pom.xml, but, it does not effect 

<dependency>
            <groupId>biz.neustar</groupId>
            <artifactId>browsermob-proxy</artifactId>
            <version>2.0-beta-7</version>
`<exclusions>`
`<exclusion>`
                   <groupId>org.eclipse.jetty</groupId> 
                                       <artifactId>jetty-util</artifactId> 
`<\exclusion>`  
`<\exclusions>`  
It seems that this is BrowswerMod issue. Please help me how to resolve this
Thanks,
Rosielover

java.lang.NoSuchMethodError: org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)V                                                                                                         at org.browsermob.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:504)
        at org.browsermob.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:372)                                at org.browsermob.proxy.http.BrowserMobHttpRequest.execute(BrowserMobHttpRequest.java:157)
        at org.browsermob.proxy.BrowserMobProxyHandler.proxyPlainTextRequest(BrowserMobProxyHandler.java:270)                   at org.browsermob.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:185)
        at org.browsermob.proxy.jetty.http.HttpContext.handle(HttpContext.java:1509)                                            at org.browsermob.proxy.jetty.http.HttpContext.handle(HttpContext.java:1461)
        at org.browsermob.proxy.jetty.http.HttpServer.service(HttpServer.java:892)                                              at org.browsermob.proxy.jetty.http.HttpConnection.service(HttpConnection.java:815)
        at org.browsermob.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:981)
        at org.browsermob.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:832)
        at org.browsermob.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:245)
        at org.browsermob.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
        at org.browsermob.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)

**Comment by rosie78** [comment]
i resolved this
